import {
  Bell,
  BookOpen,
  BriefcaseBusiness,
  CalendarDays,
  Check,
  ClipboardCheck,
  ClipboardList,
  Download,
  Edit3,
  Eye,
  FileText,
  FlaskConical,
  GraduationCap,
  HelpCircle,
  Home,
  KeyRound,
  LayoutDashboard,
  Link2,
  LogOut,
  Mail,
  Microscope,
  PenLine,
  Plus,
  Search,
  Settings,
  ShieldCheck,
  Trash2,
  Upload,
  User,
  UserCheck,
  Users,
  X,
} from 'lucide-react'

const icons = {
  admin: ShieldCheck,
  audit: Search,
  bell: Bell,
  book: BookOpen,
  briefcase: BriefcaseBusiness,
  calendar: CalendarDays,
  check: Check,
  clipboard: ClipboardList,
  clipboardCheck: ClipboardCheck,
  download: Download,
  edit: Edit3,
  eye: Eye,
  file: FileText,
  flask: FlaskConical,
  graduation: GraduationCap,
  help: HelpCircle,
  home: Home,
  key: KeyRound,
  link: Link2,
  logout: LogOut,
  mail: Mail,
  microscope: Microscope,
  pen: PenLine,
  plus: Plus,
  search: Search,
  settings: Settings,
  upload: Upload,
  user: User,
  userCheck: UserCheck,
  users: Users,
  x: X,
  dashboard: LayoutDashboard,
  trash: Trash2,
}

export default function AppIcon({ name = 'file', size = 18, strokeWidth = 2, className = '', ...props }) {
  const Icon = icons[name] || icons.file
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" {...props} />
}
